import matplotlib.pyplot as plt

# Parameters for the LCG
m = 2**31  # modulus
a = 1103515245  # multiplier
c = 12345  # increment
seed = 42  # initial seed (X0)

# Generate a sequence of pseudorandom numbers
def linear_congruential_generator(n, seed, a, c, m):
    numbers = []
    X = seed
    for _ in range(n):
        X = (a * X + c) % m
        numbers.append(X / m)  # Normalize to [0, 1]
    return numbers

# Number of random numbers to generate
n = 10000

# Generate random numbers using LCG
random_numbers = linear_congruential_generator(n, seed, a, c, m)

# Plot the distribution
plt.figure(figsize=(10, 6))
plt.hist(random_numbers, bins=50, color='skyblue', edgecolor='black')
plt.title("Distribution of Numbers Generated by Linear Congruential Generator")
plt.xlabel("Random Number")
plt.ylabel("Frequency")
plt.show()
